### ISSUE TITLE
Drop dependency on readable-stream

### ISSUE THREAD

**Issue by JustinBeckwith** [mafintosh/duplexify#23]
It feels like the implementation of streams in Node.js 6+ has settled down a great deal.  Would you consider a PR to drop the dependency on the user space implementation of `readable-stream`?  Or are there good reasons to keep on using it?

**Comment by phated** [comment]
https://r.va.gg/2014/06/why-i-dont-use-nodes-core-stream-module.html

**Comment by mafintosh** [comment]
Being part of the streams working group readable-stream is still very much needed as there and bigger changes still happening underneat the hood of streams

**Comment by JustinBeckwith** [comment]
Thanks!  Can you give a TL;DR of what those changes look like?  We're trying to evaluate our usage of streams across all of the Google npm modules, and I find myself often conflicted 😁

**Comment by phated** [comment]
I'll let mafintosh speak to changes but I'm going to close this so it doesn't show up on my github dashboard.
