### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by JustinBeckwith** [mafintosh/duplexify#24]
It would be rad if this library was written in TypeScript.  I'd be happy to do the work and submit a PR if that would be welcomed :) This would make it easier to include a `d.ts` file for other TypeScript users, as well as the other TypeScript type advantages.  

Would you be open to accepting a PR? I've prototyped it here.
https://github.com/JustinBeckwith/duplexify

**Comment by callmehiphop** [comment]
I can understand if they'd want to keep this vanilla, but I'm curious if a PR containing just a declaration file would be accepted?

**Comment by mafintosh** [comment]
a ts file is fine, as long as there isn't any real maintenance burden with that.
